[package]
name = "newtype_pattern"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Examples demonstrating the newtype pattern in Rust"
[dependencies]
